#!/bin/bash
# number of threads:
for t in 1 2 4
do
	echo NUMT = $t
	# number of subdivisions:
	for s in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
	do
		echo NUM = $s
		gcc-7 -DNUM=$s -DNUMT=$t Proj3.cpp -o prog -lm -fopenmp
		./prog
	done
done
