#!/bin/bash
# number of threads:
for t in 1 2 4 6 8
do
	echo NUMT = $t
	# number of subdivisions:
	for s in 16 32 64 128 256 512 1024 2048 3072 4096
	do
		echo NUMNODES = $s
		gcc-7 -DNUMNODES=$s -DNUMT=$t Proj1.cpp -o prog -lm -fopenmp
		./prog
	done
done
